In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from rdkit import Chem, DataStructs
from rdkit.Chem import (
    PandasTools,
    Draw,
    Descriptors,
    MACCSkeys,
    rdFingerprintGenerator,
    rdMolDescriptors
)

import matplotlib.pyplot as plt

In [90]:
molecules  = pd.read_csv(r"E:\Projects\Mycobacterium tuberculosis\ML performance comparison\Input files\te_df_64.csv")

In [91]:
molecules.head()

,Molecule ChEMBL ID,MIC,Units,Smiles,Label
0,CHEMBL4076166,64.00,ug.mL-1,CSc1ccc2c(c1)N(CCC1CCCCN1C(C)C)c1ccccc1S2,0
1,CHEMBL2393487,16.00,ug.mL-1,Cc1cccc(-c2cn(C[C@H]3CN(c4ccc(N5CCN(Cc6cc(-c7c...,0
2,CHEMBL1269430,0.63,ug.mL-1,COC(=O)/C=C1\Nc2ccc(F)cc2OC1=O,1
3,CHEMBL5395017,8.00,ug.mL-1,COc1ccc(-c2ccn(-c3ccc(NC(=S)NCc4ccccc4)cc3)n2)...,1
4,CHEMBL4228114,50.00,ug.mL-1,O=C(/C=C/c1ccc(F)cc1)Nc1nc(-c2ccc3oc4ccccc4c3c...,0

In [92]:
PandasTools.AddMoleculeColumnToFrame(molecules, smilesCol="Smiles")

In [93]:
# get ecfp4 FP
fpg = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=1024)
molecules["ecfp4"] = molecules["ROMol"].apply(lambda m: fpg.GetFingerprint(m)) #bit

In [94]:
print(len(molecules["ecfp4"].iloc[0]))

1024

In [95]:
ecfp4_df = pd.DataFrame([list(i.ToBitString()) for i in molecules["ecfp4"]], columns=[f"ECFP4_{i}" for i in range(1024)])
molecules_ecfp4 = pd.concat([molecules.iloc[:,:5], ecfp4_df], axis=1)

In [96]:
molecules_ecfp4.head()

,Molecule ChEMBL ID,MIC,Units,Smiles,Label,ECFP4_0,ECFP4_1,ECFP4_2,ECFP4_3,ECFP4_4,...,ECFP4_1014,ECFP4_1015,ECFP4_1016,ECFP4_1017,ECFP4_1018,ECFP4_1019,ECFP4_1020,ECFP4_1021,ECFP4_1022,ECFP4_1023
0,CHEMBL4076166,64.00,ug.mL-1,CSc1ccc2c(c1)N(CCC1CCCCN1C(C)C)c1ccccc1S2,0,0,1,0,0,1,...,0,0,0,0,0,1,1,0,0,0
1,CHEMBL2393487,16.00,ug.mL-1,Cc1cccc(-c2cn(C[C@H]3CN(c4ccc(N5CCN(Cc6cc(-c7c...,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,CHEMBL1269430,0.63,ug.mL-1,COC(=O)/C=C1\Nc2ccc(F)cc2OC1=O,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL5395017,8.00,ug.mL-1,COc1ccc(-c2ccn(-c3ccc(NC(=S)NCc4ccccc4)cc3)n2)...,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL4228114,50.00,ug.mL-1,O=C(/C=C/c1ccc(F)cc1)Nc1nc(-c2ccc3oc4ccccc4c3c...,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [97]:
molecules_ecfp4.to_csv(r"E:\Projects\Mycobacterium tuberculosis\ML performance comparison\te_64_ecfp.csv",index=False)