In [1]:
from rdkit import Chem
import pandas as pd
import numpy as np

In [2]:
molecules  = pd.read_csv(r"E:\Projects\Mycobacterium tuberculosis\02-Generate Standard Smile\input\bio_12756.csv")

In [3]:
molecules

,Molecule ChEMBL ID,Smiles,Standard Type,MIC,Units
0,CHEMBL1086385,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...,MIC,0.120,ug.mL-1
1,CHEMBL1086383,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...,MIC,2.000,ug.mL-1
2,CHEMBL225164,Oc1ccc(Cl)c2cccnc12,MIC,0.125,ug.mL-1
3,CHEMBL497,Oc1c(I)cc(Cl)c2cccnc12,MIC,6.250,ug.mL-1
4,CHEMBL4061841,NC(=O)C1CCN(Cc2c(-c3ccccc3)[nH]c3ccnc(Cl)c23)CC1,MIC,25.000,ug.mL-1
...,...,...,...,...,...
12751,CHEMBL5517699,CCOc1cc(/C=N/C2=C(Cl)C(=O)c3ccccc3C2=O)ccc1O,MIC,6.250,ug.mL-1
12752,CHEMBL5572792,COc1cc([C@@](O)(CCN(C)C)[C@H](c2cc3cc(Br)ccc3n...,MIC,0.004,ug.mL-1
12753,CHEMBL4854563,CO[C@H]1CC=C2C(=O)c3c(cc(C)c(-c4c(C)cc5c(c4O)C...,MIC,25.000,ug.mL-1
12754,CHEMBL4864131,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1ccc(C(=O)N2CCOCC2...,MIC,1.660,ug.mL-1
12755,CHEMBL4864122,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1cc(C(=O)N2CCCCC2)...,MIC,137.000,ug.mL-1

In [4]:
print(molecules.isnull().sum())

Molecule ChEMBL ID    0
Smiles                0
Standard Type         0
MIC                   0
Units                 0
dtype: int64

In [5]:
def convert_to_valid_smiles(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        return Chem.MolToSmiles(mol)
    else:
        return None

In [6]:
molecules['Standard_smiles'] = molecules['Smiles'].apply(convert_to_valid_smiles)

In [7]:
molecules.shape

(12756, 6)

In [8]:
molecules.head()

,Molecule ChEMBL ID,Smiles,Standard Type,MIC,Units,Standard_smiles
0,CHEMBL1086385,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...,MIC,0.120,ug.mL-1,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...
1,CHEMBL1086383,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...,MIC,2.000,ug.mL-1,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...
2,CHEMBL225164,Oc1ccc(Cl)c2cccnc12,MIC,0.125,ug.mL-1,Oc1ccc(Cl)c2cccnc12
3,CHEMBL497,Oc1c(I)cc(Cl)c2cccnc12,MIC,6.250,ug.mL-1,Oc1c(I)cc(Cl)c2cccnc12
4,CHEMBL4061841,NC(=O)C1CCN(Cc2c(-c3ccccc3)[nH]c3ccnc(Cl)c23)CC1,MIC,25.000,ug.mL-1,NC(=O)C1CCN(Cc2c(-c3ccccc3)[nH]c3ccnc(Cl)c23)CC1

In [9]:
valid_molecules = molecules[molecules['Standard_smiles'].notnull()]

In [10]:
valid_molecules

,Molecule ChEMBL ID,Smiles,Standard Type,MIC,Units,Standard_smiles
0,CHEMBL1086385,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...,MIC,0.120,ug.mL-1,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...
1,CHEMBL1086383,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...,MIC,2.000,ug.mL-1,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...
2,CHEMBL225164,Oc1ccc(Cl)c2cccnc12,MIC,0.125,ug.mL-1,Oc1ccc(Cl)c2cccnc12
3,CHEMBL497,Oc1c(I)cc(Cl)c2cccnc12,MIC,6.250,ug.mL-1,Oc1c(I)cc(Cl)c2cccnc12
4,CHEMBL4061841,NC(=O)C1CCN(Cc2c(-c3ccccc3)[nH]c3ccnc(Cl)c23)CC1,MIC,25.000,ug.mL-1,NC(=O)C1CCN(Cc2c(-c3ccccc3)[nH]c3ccnc(Cl)c23)CC1
...,...,...,...,...,...,...
12751,CHEMBL5517699,CCOc1cc(/C=N/C2=C(Cl)C(=O)c3ccccc3C2=O)ccc1O,MIC,6.250,ug.mL-1,CCOc1cc(/C=N/C2=C(Cl)C(=O)c3ccccc3C2=O)ccc1O
12752,CHEMBL5572792,COc1cc([C@@](O)(CCN(C)C)[C@H](c2cc3cc(Br)ccc3n...,MIC,0.004,ug.mL-1,COc1cc([C@@](O)(CCN(C)C)[C@H](c2cc3cc(Br)ccc3n...
12753,CHEMBL4854563,CO[C@H]1CC=C2C(=O)c3c(cc(C)c(-c4c(C)cc5c(c4O)C...,MIC,25.000,ug.mL-1,CO[C@H]1CC=C2C(=O)c3c(cc(C)c(-c4c(C)cc5c(c4O)C...
12754,CHEMBL4864131,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1ccc(C(=O)N2CCOCC2...,MIC,1.660,ug.mL-1,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1ccc(C(=O)N2CCOCC2...
12755,CHEMBL4864122,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1cc(C(=O)N2CCCCC2)...,MIC,137.000,ug.mL-1,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1cc(C(=O)N2CCCCC2)...

In [11]:
valid_molecules = valid_molecules.drop_duplicates("Standard_smiles", keep="first")

In [12]:
valid_molecules

,Molecule ChEMBL ID,Smiles,Standard Type,MIC,Units,Standard_smiles
0,CHEMBL1086385,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...,MIC,0.120,ug.mL-1,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...
1,CHEMBL1086383,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...,MIC,2.000,ug.mL-1,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...
2,CHEMBL225164,Oc1ccc(Cl)c2cccnc12,MIC,0.125,ug.mL-1,Oc1ccc(Cl)c2cccnc12
3,CHEMBL497,Oc1c(I)cc(Cl)c2cccnc12,MIC,6.250,ug.mL-1,Oc1c(I)cc(Cl)c2cccnc12
4,CHEMBL4061841,NC(=O)C1CCN(Cc2c(-c3ccccc3)[nH]c3ccnc(Cl)c23)CC1,MIC,25.000,ug.mL-1,NC(=O)C1CCN(Cc2c(-c3ccccc3)[nH]c3ccnc(Cl)c23)CC1
...,...,...,...,...,...,...
12751,CHEMBL5517699,CCOc1cc(/C=N/C2=C(Cl)C(=O)c3ccccc3C2=O)ccc1O,MIC,6.250,ug.mL-1,CCOc1cc(/C=N/C2=C(Cl)C(=O)c3ccccc3C2=O)ccc1O
12752,CHEMBL5572792,COc1cc([C@@](O)(CCN(C)C)[C@H](c2cc3cc(Br)ccc3n...,MIC,0.004,ug.mL-1,COc1cc([C@@](O)(CCN(C)C)[C@H](c2cc3cc(Br)ccc3n...
12753,CHEMBL4854563,CO[C@H]1CC=C2C(=O)c3c(cc(C)c(-c4c(C)cc5c(c4O)C...,MIC,25.000,ug.mL-1,CO[C@H]1CC=C2C(=O)c3c(cc(C)c(-c4c(C)cc5c(c4O)C...
12754,CHEMBL4864131,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1ccc(C(=O)N2CCOCC2...,MIC,1.660,ug.mL-1,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1ccc(C(=O)N2CCOCC2...
12755,CHEMBL4864122,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1cc(C(=O)N2CCCCC2)...,MIC,137.000,ug.mL-1,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1cc(C(=O)N2CCCCC2)...

In [13]:
valid_molecules.shape

(12756, 6)

In [15]:
valid_molecules = pd.DataFrame(
    {'Molecule ChEMBL ID':valid_molecules.loc[:,'Molecule ChEMBL ID'],
     'MIC':valid_molecules.loc[:,'MIC'],
     'Units':valid_molecules.loc[:,'Units'],
     'Smiles':valid_molecules.loc[:,'Standard_smiles']
    }
)

In [16]:
valid_molecules

,Molecule ChEMBL ID,MIC,Units,Smiles
0,CHEMBL1086385,0.120,ug.mL-1,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...
1,CHEMBL1086383,2.000,ug.mL-1,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...
2,CHEMBL225164,0.125,ug.mL-1,Oc1ccc(Cl)c2cccnc12
3,CHEMBL497,6.250,ug.mL-1,Oc1c(I)cc(Cl)c2cccnc12
4,CHEMBL4061841,25.000,ug.mL-1,NC(=O)C1CCN(Cc2c(-c3ccccc3)[nH]c3ccnc(Cl)c23)CC1
...,...,...,...,...
12751,CHEMBL5517699,6.250,ug.mL-1,CCOc1cc(/C=N/C2=C(Cl)C(=O)c3ccccc3C2=O)ccc1O
12752,CHEMBL5572792,0.004,ug.mL-1,COc1cc([C@@](O)(CCN(C)C)[C@H](c2cc3cc(Br)ccc3n...
12753,CHEMBL4854563,25.000,ug.mL-1,CO[C@H]1CC=C2C(=O)c3c(cc(C)c(-c4c(C)cc5c(c4O)C...
12754,CHEMBL4864131,1.660,ug.mL-1,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1ccc(C(=O)N2CCOCC2...
12755,CHEMBL4864122,137.000,ug.mL-1,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1cc(C(=O)N2CCCCC2)...

In [ ]:
min_value = valid_molecules['MIC'].min()
max_value = valid_molecules['MIC'].max()

median_value = valid_molecules["MIC"].median()
mean_value = valid_molecules["MIC"].mean()

In [18]:
def classify_resistance(row):
    #drug = str(row["Molecule Name"]).upper()
    mic = row["MIC"]
    return 0 if mic >= median_value else 1

In [19]:
valid_molecules["Label"] = valid_molecules.apply(classify_resistance, axis=1)

In [20]:
valid_molecules

,Molecule ChEMBL ID,MIC,Units,Smiles,Label
0,CHEMBL1086385,0.120,ug.mL-1,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...,1
1,CHEMBL1086383,2.000,ug.mL-1,CCCCCCCC[C@@H](C)C(=O)N1CCC[C@H]1C(=O)N[C@@H](...,1
2,CHEMBL225164,0.125,ug.mL-1,Oc1ccc(Cl)c2cccnc12,1
3,CHEMBL497,6.250,ug.mL-1,Oc1c(I)cc(Cl)c2cccnc12,1
4,CHEMBL4061841,25.000,ug.mL-1,NC(=O)C1CCN(Cc2c(-c3ccccc3)[nH]c3ccnc(Cl)c23)CC1,0
...,...,...,...,...,...
12751,CHEMBL5517699,6.250,ug.mL-1,CCOc1cc(/C=N/C2=C(Cl)C(=O)c3ccccc3C2=O)ccc1O,1
12752,CHEMBL5572792,0.004,ug.mL-1,COc1cc([C@@](O)(CCN(C)C)[C@H](c2cc3cc(Br)ccc3n...,1
12753,CHEMBL4854563,25.000,ug.mL-1,CO[C@H]1CC=C2C(=O)c3c(cc(C)c(-c4c(C)cc5c(c4O)C...,0
12754,CHEMBL4864131,1.660,ug.mL-1,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1ccc(C(=O)N2CCOCC2...,1
12755,CHEMBL4864122,137.000,ug.mL-1,CCOC(=O)NC(=O)c1ccsc1NC(=O)c1cc(C(=O)N2CCCCC2)...,0

In [21]:
valid_molecules['Label'].value_counts()

Label
0    6645
1    6111
Name: count, dtype: int64

In [22]:
valid_molecules.to_csv(r'E:\Projects\Mycobacterium tuberculosis\02-Generate Standard Smile\Valid_12756.csv',index = False)